#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="/etc/sing-box"
INSTALL_DIR="/opt/singbox-rule-ui"
MANAGER_DIR="$CONFIG_DIR/manager"
INSTALL_STATE_FILE="$MANAGER_DIR/install-state"
RADVD_STATE_FILE="$MANAGER_DIR/radvd-state.before-sing-box"
APT_PACKAGES=(curl ca-certificates tar gzip python3 nftables iproute2 rsync util-linux)
PURGE=0
ASSUME_YES=0

usage() {
  cat <<'EOF'
Usage:
  sudo bash scripts/uninstall.sh [--purge] [--yes]

Default uninstall removes sing-box-gateway-ui services, helper scripts, runtime
config, generated rules, UI files, and the bundled sing-box binary when this
installer added it. It also removes apt packages that were absent before this
installer added them. If sing-box or an apt package existed before installation,
it is kept.

Use --purge to also remove /usr/local/bin/sing-box even when ownership cannot
be proven from the install state.
EOF
}

need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root." >&2
    exit 1
  fi
}

ask_confirm() {
  if [ "$ASSUME_YES" = "1" ]; then
    return 0
  fi
  if [ ! -r /dev/tty ]; then
    echo "No interactive terminal. Re-run with --yes to confirm." >&2
    exit 1
  fi
  prompt="Uninstall sing-box-gateway-ui and stop gateway services?"
  if [ "$PURGE" = "1" ]; then
    prompt="PURGE all sing-box-gateway-ui files, configs, and /usr/local/bin/sing-box?"
  else
    prompt="Uninstall sing-box-gateway-ui and remove all files installed by it?"
  fi
  printf "%s [y/N]: " "$prompt" > /dev/tty
  read -r answer < /dev/tty
  case "$answer" in
    y|Y|yes|YES) ;;
    *) echo "Cancelled."; exit 0 ;;
  esac
}

run_systemctl() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl "$@" >/dev/null 2>&1 || true
  fi
}

cleanup_tproxy_runtime() {
  if command -v nft >/dev/null 2>&1; then
    nft delete table inet singbox_tproxy >/dev/null 2>&1 || true
    nft delete table inet singbox >/dev/null 2>&1 || true
  fi
  ip rule del fwmark 1 table 100 >/dev/null 2>&1 || true
  ip -6 rule del fwmark 1 table 100 >/dev/null 2>&1 || true
  ip route flush table 100 >/dev/null 2>&1 || true
  ip -6 route flush table 100 >/dev/null 2>&1 || true
}

restore_host_resolver() {
  # 卸载不回滚 systemd-resolved 的 DNSStubListener=no，保留 53 端口关闭保护状态。
  return 0
}

state_value() {
  local key="$1" file="$2"
  [ -r "$file" ] || return 0
  awk -F= -v key="$key" '$1 == key { print substr($0, length(key) + 2); exit }' "$file"
}

restore_radvd_state() {
  if ! command -v systemctl >/dev/null 2>&1 || ! systemctl list-unit-files radvd.service >/dev/null 2>&1; then
    return
  fi
  if [ ! -r "$RADVD_STATE_FILE" ]; then
    return
  fi
  before_enabled="$(state_value enabled "$RADVD_STATE_FILE")"
  before_active="$(state_value active "$RADVD_STATE_FILE")"

  # 只按安装前记录恢复 radvd；没有记录时不主动开启 IPv6 RA 广播。
  case "$before_enabled" in
    masked)
      run_systemctl mask radvd.service
      ;;
    enabled|enabled-runtime|linked|linked-runtime|alias)
      run_systemctl unmask radvd.service
      run_systemctl enable radvd.service
      ;;
    disabled|static|indirect|generated|transient|"")
      run_systemctl unmask radvd.service
      run_systemctl disable radvd.service
      ;;
    *)
      run_systemctl unmask radvd.service
      run_systemctl disable radvd.service
      ;;
  esac

  if [ "$before_active" = "active" ]; then
    run_systemctl start radvd.service
  else
    run_systemctl stop radvd.service
  fi
}

remove_generated_radvd_files() {
  for path in /etc/radvd.conf /etc/radvd.conf.bak.* /etc/radvd.conf.bak-restore-rdnss-*; do
    [ -e "$path" ] || continue
    if head -n 1 "$path" 2>/dev/null | grep -q "Generated by Sing-box UI"; then
      rm -f "$path"
    fi
  done
}

remove_sing_box_binary_if_owned() {
  owner="$(state_value sing_box_binary "$INSTALL_STATE_FILE")"
  if [ "$owner" = "installed" ] || { [ "$owner" = "" ] && [ "$PURGE" = "1" ]; }; then
    rm -f /usr/local/bin/sing-box
  fi
}

remove_installed_packages_if_owned() {
  if ! command -v apt-get >/dev/null 2>&1; then
    return
  fi
  packages_to_remove=()
  for package in "${APT_PACKAGES[@]}"; do
    if [ "$(state_value "apt_${package}" "$INSTALL_STATE_FILE")" = "absent" ]; then
      packages_to_remove+=("$package")
    fi
  done
  if [ "${#packages_to_remove[@]}" -eq 0 ]; then
    return
  fi
  # 只卸载安装前不存在、由本安装器引入的依赖，避免误删系统原有基础包。
  apt-get purge -y "${packages_to_remove[@]}" || true
  apt-get autoremove -y || true
}

parse_args() {
  for arg in "$@"; do
    case "$arg" in
      --purge) PURGE=1 ;;
      -y|--yes) ASSUME_YES=1 ;;
      -h|--help) usage; exit 0 ;;
      *) echo "Unknown option: $arg" >&2; usage >&2; exit 1 ;;
    esac
  done
}

main() {
  parse_args "$@"
  need_root
  ask_confirm

  echo "Stopping services..."
  run_systemctl disable --now update-sing-box-rules-jsdelivr.timer
  run_systemctl disable --now update-sing-box-rules-jsdelivr.service
  run_systemctl disable --now singbox-rule-ui.service
  run_systemctl disable --now sing-box.service
  run_systemctl disable --now sing-box-tproxy.service

  cleanup_tproxy_runtime
  restore_host_resolver
  restore_radvd_state

  echo "Removing service files and helper scripts..."
  rm -f \
    /etc/systemd/system/sing-box.service \
    /etc/systemd/system/sing-box-tproxy.service \
    /etc/systemd/system/singbox-rule-ui.service \
    /etc/systemd/system/update-sing-box-rules-jsdelivr.service \
    /etc/systemd/system/update-sing-box-rules-jsdelivr.timer \
    /usr/local/sbin/sing-box-tproxy-setup \
    /usr/local/sbin/refresh-sing-box-runtime-config \
    /usr/local/sbin/refresh-sing-box-tproxy-setup \
    /usr/local/sbin/update-sing-box-rules-jsdelivr \
    /usr/local/bin/sing-box-gateway-info \
    /usr/local/bin/sing-box-gateway-uninstall \
    /etc/systemd/journald.conf.d/90-sing-box-gateway.conf \
    /etc/sysctl.d/99-sing-box-tproxy.conf

  remove_generated_radvd_files
  rm -rf "$INSTALL_DIR"
  remove_sing_box_binary_if_owned
  remove_installed_packages_if_owned
  rm -rf "$CONFIG_DIR"

  run_systemctl daemon-reload
  echo "Uninstalled."
}

main "$@"
